### ISSUE TITLE
Tetra items need addon mod to work with Epic Fight

### ISSUE THREAD

**Issue by Halfshot555** [Pingu-Pox/duncraft-reborn#13]
**Describe the bug**
Epic fight is not detecting Tetra items and defaulting to unarmed combat animations

Searching for solution brought me to this addon mod for Epic Fight
https://www.curseforge.com/minecraft/mc-mods/epic-fight-nbt-integration#:~:text=This%20is%20mainly%20useful%20for,can%20now%20use%20default%20configs

**Desktop (please complete the following information):**
 - Version 0.1.10

**Comment by Pingu-Pox** [comment]
This was removed in an earlier version due to console bloat (should probably get around to letting the author know, but been busy). It will make a return eventually, it's sitting in the server's disabled mods folder. Will add "Readd Epic Fight NBT Integration" to the dev trello board so I don't forget.
